# ----------------------------------------------
# Inventory service: http://localhost:8082
# Order service: http://localhost:8083
# Order-service depends on inventory
# -----------------------------------------------

name: coffee_shop_app

services:
  inventory-service:

  order-service:


networks: