# ----------------------------------------------
# Inventory service: http://localhost:8082
# Order service: http://localhost:8083
# Order-service depends on inventory
# -----------------------------------------------

version: '3.9'

services:
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile.inventory
    ports:
      - "8082:8082"
    container_name: inventory-service
    networks:
      - app-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile.order
    ports:
      - "8083:8080"
    environment:
      INVENTORY_URL: http://inventory-service:8082     
    container_name: order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
