version: "3.9"

# Define all services in this multi-stage setup
services:

  # Frontend service
  frontend:
    build:
      context: ./frontend   # Path to the React app
      dockerfile: Dockerfile
    ports:
      - "3000:80"           # Expose port 80 of the container as 3000 on the host
    depends_on:
      - backend             # Ensure backend starts before the frontend
    volumes:
      - ./frontend:/usr/src/app # Mount code for local development
    networks:
      - app-network         # Use the shared network

  # Backend service
  backend:
    build:
      context: ./backend    # Path to the Node.js app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"         # Map port 5000 for the backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    depends_on:
      - db                  # Ensure database starts before backend
    networks:
      - app-network

  # Database service
  db:
    image: postgres:15      # Official PostgreSQL image
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./db-data:/var/lib/postgresql/data # Persistent storage for the database
    networks:
      - app-network

# Define a shared network
networks:
  app-network:
    driver: bridge
