version: "3.9"
name: wordpress-demo

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress-data:/var/www/html
    networks:
      - wordpress-network

  db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80" # Map port 80 in the container to port 8081 on the host
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress-network

volumes:
  wordpress-data:
  db-data:

networks:
  wordpress-network:
    driver: bridge
